# Generated by Django 3.0 on 2022-12-31 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcount',
            name='like_or_dislike',
        ),
        migrations.CreateModel(
            name='PostLikeBy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
