# Generated by Django 4.1 on 2023-01-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_auto_20221231_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlikeby",
            name="dislike",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postlikeby",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
