# Generated by Django 4.1 on 2023-01-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0003_alter_postlikeby_dislike_alter_postlikeby_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcount",
            old_name="dislikes",
            new_name="dislike",
        ),
        migrations.RenameField(
            model_name="postcount",
            old_name="likes",
            new_name="like",
        ),
    ]
